name: test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

cache-mode: none

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm run test
